### ISSUE TITLE
Seems do not support rpm very well

### ISSUE THREAD

**Issue by tvvocold** [ctron/package-drone-openshift#2]
cannot check the metadata or relations.

**Comment by ctron** [comment]
RPM is not implemented as of now.

Please see https://github.com/ctron/package-drone/issues/16

**Comment by tvvocold** [comment]
When will rpm be support?

**Comment by ctron** [comment]
Up to now there is no plan. However everybody is welcome to contribute :wink: And I will be glad to help you get started if you like.

**Comment by tvvocold** [comment]
Sry, don' t know about java.

**Comment by tvvocold** [comment]
Plz ping me if pd support rpm.

**Comment by ctron** [comment]
Just subscribe to issue ctron/package-drone#16 and you will get automatically notified when something happens.

May I ask what you would like to do with this feature, just to better understand you use case.

**Comment by tvvocold** [comment]
Coz we got a [build system](http://copr.fdzh.org/) might use pd as a hub.

**Comment by ctron** [comment]
Just to let you know, the next version of Package Drone will have support for RPM and YUM.

See ctron/package-drone#16

**Comment by tvvocold** [comment]
Cool! 
When will that version release?

**Comment by ctron** [comment]
There is no date defined up to now. However I think it will be in the next two or three weeks.

**Comment by tvvocold** [comment]
Thx for your work!

**Comment by tvvocold** [comment]
BTW, Can i add package drone into [this list](https://github.com/httpsGithubParty/FOSS-for-Dev)?

**Comment by ctron** [comment]
Sure

**Comment by ctron** [comment]
There is now a milestone release for Package Drone which contains support for RPM: https://github.com/ctron/package-drone/releases/tag/v0.10.0-m2

**Comment by tvvocold** [comment]
Wonderful, Nj！

On 周二, 6月 9, 2015 at 17:33, ctron/package-drone-openshift
reply@reply.github.com
wrote:
There is now a milestone release for Package Drone which contains support for
RPM: https://github.com/ctron/package-drone/releases/tag/v0.10.0-m2
[https://github.com/ctron/package-drone/releases/tag/v0.10.0-m2]

—
Reply to this email directly or view it on GitHub
[https://github.com/ctron/package-drone-openshift/issues/2#issuecomment-110293691] .[https://github.com/notifications/beacon/AEUha57hsbcoQ4WmnIQUtM-8oZbdustMks5oRqpogaJpZM4DrE5Q.gif]
