### ISSUE TITLE
QuickStart fails to deploy, appears to be exceeding the 1GB disk quota

### ISSUE THREAD

**Issue by luciddreamz** [ctron/package-drone-openshift#3]
This QuickStart currently fails to deploy on OpenShift Online. It appears to be exceeding the 1GB disk quota during deployment: "Warning: Gear 55562798e0b8cdce1a00022c is using 100.0% of disk quota"

**Comment by ctron** [comment]
I will check this tomorrow.

**Comment by ctron** [comment]
Seems like the git repository has about 1 GB when it is checked out.

So I will clear out the old versions and leave the last two. I would really like to figure out how to do proper updates with openshift.

**Comment by ctron** [comment]
Ok, cleaning out the old versions in the git repository did work.

It should be possible again to create new instances.
